/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'answerText' : string,
  'answeredAt' : Time,
  'answeredBy' : string,
}
export type Category = { 'generalStudies' : null } |
  { 'other' : string } |
  { 'csat' : null } |
  { 'currentAffairs' : null } |
  { 'interviewPrep' : null } |
  { 'essayWriting' : null } |
  { 'optionalSubject' : string };
export interface Course {
  'id' : CourseId,
  'title' : string,
  'description' : string,
  'lessons' : Array<Lesson>,
  'educatorName' : string,
  'category' : Category,
  'price' : bigint,
  'durationWeeks' : bigint,
}
export type CourseId = bigint;
export interface Doubt {
  'id' : DoubtId,
  'postedAt' : Time,
  'answer' : [] | [Answer],
  'questionText' : string,
  'student' : Principal,
  'course' : CourseId,
}
export type DoubtId = bigint;
export interface Enrollment {
  'id' : EnrollmentId,
  'completedLessonIds' : Array<LessonId>,
  'student' : Principal,
  'enrollmentDate' : Time,
  'courseId' : CourseId,
}
export type EnrollmentId = bigint;
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'courseId' : CourseId,
}
export type LessonId = bigint;
export interface NewCourse {
  'title' : string,
  'description' : string,
  'lessons' : Array<NewLesson>,
  'educatorName' : string,
  'category' : string,
  'price' : bigint,
  'durationWeeks' : bigint,
}
export interface NewLesson {
  'title' : string,
  'content' : string,
  'order' : bigint,
}
export interface TestScore {
  'marks' : bigint,
  'totalMarks' : bigint,
  'subject' : string,
  'takenAt' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<[NewCourse], Course>,
  'enrollStudentInCourse' : ActorMethod<[CourseId], Enrollment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseById' : ActorMethod<[CourseId], Course>,
  'getCourseDoubtsList' : ActorMethod<[CourseId], Array<Doubt>>,
  'getStudentEnrollmentsList' : ActorMethod<[Principal], Array<Enrollment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTestScores' : ActorMethod<[Principal], Array<TestScore>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'markLessonComplete' : ActorMethod<[CourseId, LessonId], undefined>,
  'postDoubt' : ActorMethod<[CourseId, string], Doubt>,
  'postDoubtAnswer' : ActorMethod<[DoubtId, string, string], Doubt>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitTestScore' : ActorMethod<[string, bigint, bigint], TestScore>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];