/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewLesson = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
});
export const NewCourse = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(NewLesson),
  'educatorName' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'durationWeeks' : IDL.Nat,
});
export const CourseId = IDL.Nat;
export const LessonId = IDL.Nat;
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'courseId' : CourseId,
});
export const Category = IDL.Variant({
  'generalStudies' : IDL.Null,
  'other' : IDL.Text,
  'csat' : IDL.Null,
  'currentAffairs' : IDL.Null,
  'interviewPrep' : IDL.Null,
  'essayWriting' : IDL.Null,
  'optionalSubject' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'educatorName' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'durationWeeks' : IDL.Nat,
});
export const EnrollmentId = IDL.Nat;
export const Time = IDL.Int;
export const Enrollment = IDL.Record({
  'id' : EnrollmentId,
  'completedLessonIds' : IDL.Vec(LessonId),
  'student' : IDL.Principal,
  'enrollmentDate' : Time,
  'courseId' : CourseId,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const DoubtId = IDL.Nat;
export const Answer = IDL.Record({
  'answerText' : IDL.Text,
  'answeredAt' : Time,
  'answeredBy' : IDL.Text,
});
export const Doubt = IDL.Record({
  'id' : DoubtId,
  'postedAt' : Time,
  'answer' : IDL.Opt(Answer),
  'questionText' : IDL.Text,
  'student' : IDL.Principal,
  'course' : CourseId,
});
export const TestScore = IDL.Record({
  'marks' : IDL.Nat,
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'takenAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func([NewCourse], [Course], []),
  'enrollStudentInCourse' : IDL.Func([CourseId], [Enrollment], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseById' : IDL.Func([CourseId], [Course], ['query']),
  'getCourseDoubtsList' : IDL.Func([CourseId], [IDL.Vec(Doubt)], ['query']),
  'getStudentEnrollmentsList' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTestScores' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TestScore)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
  'postDoubt' : IDL.Func([CourseId, IDL.Text], [Doubt], []),
  'postDoubtAnswer' : IDL.Func([DoubtId, IDL.Text, IDL.Text], [Doubt], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTestScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [TestScore], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewLesson = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
  });
  const NewCourse = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(NewLesson),
    'educatorName' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'durationWeeks' : IDL.Nat,
  });
  const CourseId = IDL.Nat;
  const LessonId = IDL.Nat;
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'courseId' : CourseId,
  });
  const Category = IDL.Variant({
    'generalStudies' : IDL.Null,
    'other' : IDL.Text,
    'csat' : IDL.Null,
    'currentAffairs' : IDL.Null,
    'interviewPrep' : IDL.Null,
    'essayWriting' : IDL.Null,
    'optionalSubject' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'educatorName' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'durationWeeks' : IDL.Nat,
  });
  const EnrollmentId = IDL.Nat;
  const Time = IDL.Int;
  const Enrollment = IDL.Record({
    'id' : EnrollmentId,
    'completedLessonIds' : IDL.Vec(LessonId),
    'student' : IDL.Principal,
    'enrollmentDate' : Time,
    'courseId' : CourseId,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const DoubtId = IDL.Nat;
  const Answer = IDL.Record({
    'answerText' : IDL.Text,
    'answeredAt' : Time,
    'answeredBy' : IDL.Text,
  });
  const Doubt = IDL.Record({
    'id' : DoubtId,
    'postedAt' : Time,
    'answer' : IDL.Opt(Answer),
    'questionText' : IDL.Text,
    'student' : IDL.Principal,
    'course' : CourseId,
  });
  const TestScore = IDL.Record({
    'marks' : IDL.Nat,
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'takenAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func([NewCourse], [Course], []),
    'enrollStudentInCourse' : IDL.Func([CourseId], [Enrollment], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseById' : IDL.Func([CourseId], [Course], ['query']),
    'getCourseDoubtsList' : IDL.Func([CourseId], [IDL.Vec(Doubt)], ['query']),
    'getStudentEnrollmentsList' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTestScores' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TestScore)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'markLessonComplete' : IDL.Func([CourseId, LessonId], [], []),
    'postDoubt' : IDL.Func([CourseId, IDL.Text], [Doubt], []),
    'postDoubtAnswer' : IDL.Func([DoubtId, IDL.Text, IDL.Text], [Doubt], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTestScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [TestScore], []),
  });
};

export const init = ({ IDL }) => { return []; };