/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type EnrollmentId = bigint;
export type Time = bigint;
export type LessonId = bigint;
export interface NewCourse {
    title: string;
    description: string;
    lessons: Array<NewLesson>;
    educatorName: string;
    category: string;
    price: bigint;
    durationWeeks: bigint;
}
export interface Enrollment {
    id: EnrollmentId;
    completedLessonIds: Array<LessonId>;
    student: Principal;
    enrollmentDate: Time;
    courseId: CourseId;
}
export interface Course {
    id: CourseId;
    title: string;
    description: string;
    lessons: Array<Lesson>;
    educatorName: string;
    category: Category;
    price: bigint;
    durationWeeks: bigint;
}
export interface NewLesson {
    title: string;
    content: string;
    order: bigint;
}
export interface Doubt {
    id: DoubtId;
    postedAt: Time;
    answer?: Answer;
    questionText: string;
    student: Principal;
    course: CourseId;
}
export interface Lesson {
    id: LessonId;
    title: string;
    content: string;
    order: bigint;
    courseId: CourseId;
}
export interface TestScore {
    marks: bigint;
    totalMarks: bigint;
    subject: string;
    takenAt: Time;
}
export type CourseId = bigint;
export interface Answer {
    answerText: string;
    answeredAt: Time;
    answeredBy: string;
}
export type DoubtId = bigint;
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export type Category = {
    __kind__: "generalStudies";
    generalStudies: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "csat";
    csat: null;
} | {
    __kind__: "currentAffairs";
    currentAffairs: null;
} | {
    __kind__: "interviewPrep";
    interviewPrep: null;
} | {
    __kind__: "essayWriting";
    essayWriting: null;
} | {
    __kind__: "optionalSubject";
    optionalSubject: string;
};
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCourse(newCourse: NewCourse): Promise<Course>;
    enrollStudentInCourse(courseId: CourseId): Promise<Enrollment>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCourseById(courseId: CourseId): Promise<Course>;
    getCourseDoubtsList(courseId: CourseId): Promise<Array<Doubt>>;
    getStudentEnrollmentsList(principal: Principal): Promise<Array<Enrollment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTestScores(principal: Principal): Promise<Array<TestScore>>;
    isCallerAdmin(): Promise<boolean>;
    listCourses(): Promise<Array<Course>>;
    markLessonComplete(courseId: CourseId, lessonId: LessonId): Promise<void>;
    postDoubt(courseId: CourseId, questionText: string): Promise<Doubt>;
    postDoubtAnswer(doubtId: DoubtId, answerText: string, answeredBy: string): Promise<Doubt>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitTestScore(subject: string, marks: bigint, totalMarks: bigint): Promise<TestScore>;
}
import type { Answer as _Answer, Category as _Category, Course as _Course, CourseId as _CourseId, Doubt as _Doubt, DoubtId as _DoubtId, Lesson as _Lesson, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCourse(arg0: NewCourse): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0);
                return from_candid_Course_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0);
            return from_candid_Course_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async enrollStudentInCourse(arg0: CourseId): Promise<Enrollment> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollStudentInCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollStudentInCourse(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseById(arg0: CourseId): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseById(arg0);
                return from_candid_Course_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseById(arg0);
            return from_candid_Course_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseDoubtsList(arg0: CourseId): Promise<Array<Doubt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseDoubtsList(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseDoubtsList(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentEnrollmentsList(arg0: Principal): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentEnrollmentsList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentEnrollmentsList(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTestScores(arg0: Principal): Promise<Array<TestScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTestScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTestScores(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async markLessonComplete(arg0: CourseId, arg1: LessonId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async postDoubt(arg0: CourseId, arg1: string): Promise<Doubt> {
        if (this.processError) {
            try {
                const result = await this.actor.postDoubt(arg0, arg1);
                return from_candid_Doubt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postDoubt(arg0, arg1);
            return from_candid_Doubt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async postDoubtAnswer(arg0: DoubtId, arg1: string, arg2: string): Promise<Doubt> {
        if (this.processError) {
            try {
                const result = await this.actor.postDoubtAnswer(arg0, arg1, arg2);
                return from_candid_Doubt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postDoubtAnswer(arg0, arg1, arg2);
            return from_candid_Doubt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitTestScore(arg0: string, arg1: bigint, arg2: bigint): Promise<TestScore> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestScore(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Doubt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Doubt): Doubt {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Answer]): Answer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DoubtId;
    postedAt: _Time;
    answer: [] | [_Answer];
    questionText: string;
    student: Principal;
    course: _CourseId;
}): {
    id: DoubtId;
    postedAt: Time;
    answer?: Answer;
    questionText: string;
    student: Principal;
    course: CourseId;
} {
    return {
        id: value.id,
        postedAt: value.postedAt,
        answer: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.answer)),
        questionText: value.questionText,
        student: value.student,
        course: value.course
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CourseId;
    title: string;
    description: string;
    lessons: Array<_Lesson>;
    educatorName: string;
    category: _Category;
    price: bigint;
    durationWeeks: bigint;
}): {
    id: CourseId;
    title: string;
    description: string;
    lessons: Array<Lesson>;
    educatorName: string;
    category: Category;
    price: bigint;
    durationWeeks: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        lessons: value.lessons,
        educatorName: value.educatorName,
        category: from_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        price: value.price,
        durationWeeks: value.durationWeeks
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generalStudies: null;
} | {
    other: string;
} | {
    csat: null;
} | {
    currentAffairs: null;
} | {
    interviewPrep: null;
} | {
    essayWriting: null;
} | {
    optionalSubject: string;
}): {
    __kind__: "generalStudies";
    generalStudies: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "csat";
    csat: null;
} | {
    __kind__: "currentAffairs";
    currentAffairs: null;
} | {
    __kind__: "interviewPrep";
    interviewPrep: null;
} | {
    __kind__: "essayWriting";
    essayWriting: null;
} | {
    __kind__: "optionalSubject";
    optionalSubject: string;
} {
    return "generalStudies" in value ? {
        __kind__: "generalStudies",
        generalStudies: value.generalStudies
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "csat" in value ? {
        __kind__: "csat",
        csat: value.csat
    } : "currentAffairs" in value ? {
        __kind__: "currentAffairs",
        currentAffairs: value.currentAffairs
    } : "interviewPrep" in value ? {
        __kind__: "interviewPrep",
        interviewPrep: value.interviewPrep
    } : "essayWriting" in value ? {
        __kind__: "essayWriting",
        essayWriting: value.essayWriting
    } : "optionalSubject" in value ? {
        __kind__: "optionalSubject",
        optionalSubject: value.optionalSubject
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Doubt>): Array<Doubt> {
    return value.map((x)=>from_candid_Doubt_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n3(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
